// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV7a-LtNCjD2o1HVwxMK5k5Z7iCXp3Gho',
    appId: '1:937026364196:web:c16e6986b7d8b9715609b1',
    messagingSenderId: '937026364196',
    projectId: 'temp-d7orbiral',
    authDomain: 'temp-d7orbiral.firebaseapp.com',
    storageBucket: 'temp-d7orbiral.appspot.com',
    measurementId: 'G-T29QDXW7ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJs2uKSodmw6-lTMHdIhDxtFOXNoa6VH4',
    appId: '1:937026364196:android:840fc85ddb3ed0075609b1',
    messagingSenderId: '937026364196',
    projectId: 'temp-d7orbiral',
    storageBucket: 'temp-d7orbiral.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBConvdzDxuOTQPDm_3-xisr0mV8uASoaw',
    appId: '1:937026364196:ios:ab322aef8dae16445609b1',
    messagingSenderId: '937026364196',
    projectId: 'temp-d7orbiral',
    storageBucket: 'temp-d7orbiral.appspot.com',
    iosClientId: '937026364196-9jnft545hhn9d5jhbnphb77lq43n87sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBConvdzDxuOTQPDm_3-xisr0mV8uASoaw',
    appId: '1:937026364196:ios:ab322aef8dae16445609b1',
    messagingSenderId: '937026364196',
    projectId: 'temp-d7orbiral',
    storageBucket: 'temp-d7orbiral.appspot.com',
    iosClientId: '937026364196-9jnft545hhn9d5jhbnphb77lq43n87sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutter',
  );
}
