// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXMmVIEmLHRJRb-aXnWNfWgsVAl5AL_CY',
    appId: '1:32968718280:web:355ba6bd61f286a5cc32fd',
    messagingSenderId: '32968718280',
    projectId: 'd7orbital-13611',
    authDomain: 'd7orbital-13611.firebaseapp.com',
    storageBucket: 'd7orbital-13611.appspot.com',
    measurementId: 'G-L0H2H0QRTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzRLKcHqIPXEmGbRgUbISrt50PtqxiZbY',
    appId: '1:32968718280:android:4eb491fd11a87d46cc32fd',
    messagingSenderId: '32968718280',
    projectId: 'd7orbital-13611',
    storageBucket: 'd7orbital-13611.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEOTBzrtw4ocrddheDKv4RIqM2kD6cVAs',
    appId: '1:32968718280:ios:fa6e473f491b0abdcc32fd',
    messagingSenderId: '32968718280',
    projectId: 'd7orbital-13611',
    storageBucket: 'd7orbital-13611.appspot.com',
    iosClientId: '32968718280-mi3dg3qudhi0kb6tgsudueajotb1ve09.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEOTBzrtw4ocrddheDKv4RIqM2kD6cVAs',
    appId: '1:32968718280:ios:fa6e473f491b0abdcc32fd',
    messagingSenderId: '32968718280',
    projectId: 'd7orbital-13611',
    storageBucket: 'd7orbital-13611.appspot.com',
    iosClientId: '32968718280-mi3dg3qudhi0kb6tgsudueajotb1ve09.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutter',
  );
}
