// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGJP6N2VUSrEESqlKTNZCR69lxia3OjRY',
    appId: '1:367985387093:web:9483ca89c7293c90ac96dc',
    messagingSenderId: '367985387093',
    projectId: 'temp-d7orbital',
    authDomain: 'temp-d7orbital.firebaseapp.com',
    storageBucket: 'temp-d7orbital.appspot.com',
    measurementId: 'G-YGZYTM7GFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-OHIp9z-w-nhftT-pCWzD61KUDBHHK1Y',
    appId: '1:367985387093:android:dc08d1649810630bac96dc',
    messagingSenderId: '367985387093',
    projectId: 'temp-d7orbital',
    storageBucket: 'temp-d7orbital.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEpUGErRqgvZYzHRbeJlksuRvBslkSR0Q',
    appId: '1:367985387093:ios:69c831b94aa13333ac96dc',
    messagingSenderId: '367985387093',
    projectId: 'temp-d7orbital',
    storageBucket: 'temp-d7orbital.appspot.com',
    iosClientId: '367985387093-q8965kci5v5hscc6vgu2a0tel5h6kpng.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEpUGErRqgvZYzHRbeJlksuRvBslkSR0Q',
    appId: '1:367985387093:ios:69c831b94aa13333ac96dc',
    messagingSenderId: '367985387093',
    projectId: 'temp-d7orbital',
    storageBucket: 'temp-d7orbital.appspot.com',
    iosClientId: '367985387093-q8965kci5v5hscc6vgu2a0tel5h6kpng.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutter',
  );
}
